# Generated by Django 4.2.1 on 2023-06-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="images",
            field=models.ImageField(blank=True, upload_to="images/"),
        ),
    ]
