# Generated by Django 4.2.1 on 2023-06-06 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_images"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="images",
            field=models.ImageField(blank=True, upload_to=""),
        ),
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="media/")),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_images",
                        to="blog.post",
                    ),
                ),
            ],
        ),
    ]
