# Generated by Django 4.2.1 on 2023-06-08 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_images_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="images",
        ),
        migrations.AddField(
            model_name="image",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(blank=True, upload_to="media/"),
        ),
    ]
